
from tkinter import * 
def submit():
    gender = gender_var.get()
    indian = indian_var.get()
    print("Gender:", gender)
    print("Indian or Not:", indian)
root = Tk()
root.title("Radio Buttons Example")
gender_var = StringVar()
indian_var = StringVar()
lable = Label(root, text="Gender:").pack()
radbtn = Radiobutton(root, text="Male", variable=gender_var, value="Male").pack()
radbtn1=Radiobutton(root, text="Female", variable=gender_var, value="Female").pack()
radbtn2=Radiobutton(root, text="Other", variable=gender_var, value="Other").pack()
label =Label(root, text="Indian or Not:").pack()
indradi=Radiobutton(root, text="Yes", variable=indian_var, value="Yes").pack()
indradi =Radiobutton(root, text="No", variable=indian_var, value="No").pack()
submit =Button(root, text="Submit", command=submit).pack()
root.mainloop()
'''from tkinter import *  
def selection():  
   selection = "You selected the option " + str(radio.get())  
   label.config(text = selection)  
def button():
    selection = "You selected the option " + str(radio.get())
    print(selection)
def button1():
    top.destroy()
top = Tk()  
top.geometry("300x150")  
radio = IntVar()  
lbl = Label(text = "Favourite programming language:")  
lbl.pack()  
R1 = Radiobutton(top, text="C", variable=radio, value=1,command=selection)  
R1.pack( anchor = W )    
R2 = Radiobutton(top, text="C++", variable=radio, value=2,command=selection)  
R2.pack( anchor = W )   
R3 = Radiobutton(top, text="Java", variable=radio, value=3,command=selection)  
R3.pack( anchor = W)    
label = Label(top)  
label.pack()  
button=Button(top,text="ok",font=("Times New Roman",20),command= button)
button.pack()
button1= Button(top,text="quit",font=('Times New Roman',20),command=button1)
button1.pack()
top.mainloop()'''